### PR TITLE
Make builds with newest Ubuntu work

### PR DESCRIPTION
**Pull request by rubenv**
This should fix builds with newer Ubuntu (#27).

I find it quite sad that these kind of changes are needed with a new distro version, but well... Ubuntu.

### CODE REVIEW

**Comment by clue** [comment]
Thanks for this PR, much appreciated :+1: 

I guess it makes sense to reference a specific Ubuntu release this time, can you amend your changes? :)

**Comment by rubenv** [comment]
@clue Done.

**Comment by clue** [comment]
Running this yields the following log results, unfortunately:

```
…
2016-07-27 13:47:52,918 INFO spawned: 'ttrss-update-daemon' with pid 22
2016-07-27 13:47:53,007 INFO exited: ttrss-update-daemon (exit status 255; not expected)
2016-07-27 13:47:54,008 INFO gave up: ttrss-update-daemon entered FATAL state, too many start retries too quickly
```

**Comment by rubenv** [comment]
Obsolete by #29

**Pull request closed without merging**
