### PR TITLE
Fix in-place upgrading of TT-RSS

### PR DESCRIPTION
**Pull request by thornbill**
This should fix permission issues preventing in-place upgrading of TT-RSS.

### CODE REVIEW

**Comment by frioux** [comment]
sadly this is likely not even worth merging: http://tt-rss.org/forum/viewtopic.php?f=10&t=3262

**Comment by clue** [comment]
Thanks for filing this PR @billt2006! :+1: 

And thanks for placing the reference here @frioux! I also stumbled upon that thread and wonder if there's still a need for this PR. Any thoughts?

**Comment by billt2006** [comment]
IMO this may still be worth merging to avoid permission issues if you try to upgrade manually.

**Comment by clue** [comment]
What is the status of this, is this still relevant?

Personally, I've always used the latest docker image, is there any point in using an alternative method?

p.s.: Sorry for the late reply :>

**Pull request closed without merging**
