### PR TITLE
Set SELF_URL_PATH on runtime

### PR DESCRIPTION
**Pull request by pschmitt**
This PR adds a new environemnt variable `SELF_URL_PATH` that can be set on runtime. Confer #14

### CODE REVIEW

**Comment by clue** [comment]
Awesome, very much appreciated! :+1: 

The README should describe *why* this variable exists and *what* value should be passed, otherwise the changes look good to me! :+1:

**Comment by stickystyle** [comment]
It would be great to see this PR merged as I've run into this myself.

**Comment by clue** [comment]
> The README should describe why this variable exists and what value should be passed, otherwise the changes look good to me! :+1:

I too would love to see this in :) This has not been merged yet because the README.md needs to be amended first. Do you happen to have any input?

**Comment by stickystyle** [comment]
Sure, I understand what needs to be written in the README.md to explain the reason for setting this. Would you like me to generate a seperate pull request for the README.md that you could merge after you merge this one? I'm not aware of a way to add commits to a pull request that is not mine.

**Comment by pschmitt** [comment]
Can this be merged now?

**Comment by clue** [comment]
> Can this be merged now?

Yeah, it's about time! :-)

**Pull request merged**
